export const knowledgeBase = {
  cabins: "🏡 Our cabins blend rustic charm with luxury — each offers a private balcony overlooking the Himalayas.",
  booking: "📅 You can book directly through our website or call our front desk for assistance with reservations.",
  restaurant: "🍽️ The Wilderness restaurant serves gourmet mountain cuisine using fresh, local ingredients.",
  spa: "💆 Our spa offers Himalayan salt therapies, aromatherapy massages, and a tranquil relaxation zone.",
  checkin: "🕒 Check-in begins at 2 PM and check-out is by 11 AM. Early check-in is available upon request.",
  checkout: "🕚 Standard check-out is 11 AM. Late check-out may be available depending on occupancy.",
  wifi: "📶 Complimentary high-speed Wi-Fi is available in all cabins and common areas.",
  activities: "🎒 Guests can enjoy trekking, stargazing, bonfires, and local cultural experiences.",
  weather: "🌤️ The weather in the Himalayas varies — mornings are cool and evenings can get chilly. Warm clothing recommended!",
  location: "📍 The Wilderness is located in the serene Himalayan foothills, about 2 hours from the nearest airport.",
  transport: "🚗 We provide pickup and drop-off services upon request. Local taxis and jeeps are also available.",
  contact: "☎️ You can reach our front desk anytime at +91-9876543210 or email us at stay@thewilderness.com.",
  pool: "🏊 Our heated infinity pool overlooks the pine forests — perfect for relaxation any time of year.",
  payment: "💳 We accept all major credit cards and UPI payments.",
  refund: "🔁 Cancellations made 48 hours before arrival are fully refundable.",
  gym: "🏋️ Our fitness center offers cardio and strength equipment with a stunning mountain view.",
  kids: "👶 Families are welcome! We have kids’ play zones, babysitting on request, and family cabins.",
  parking: "🚘 Complimentary valet parking is available for all guests.",
  breakfast: "🥐 Complimentary breakfast is served daily from 7 AM to 10 AM at our main restaurant.",
  dinner: "🍛 Dinner is served from 7 PM to 10 PM — advance reservations are recommended during weekends.",
  pets: "🐾 The Wilderness is pet-friendly! Please inform us in advance if bringing a pet.",
  bar: "🍸 Our mountain-view bar offers handcrafted cocktails and local brews — open daily from 5 PM to 11 PM.",
  honeymoon: "💞 Planning a honeymoon? Ask about our romantic packages with private dinners and spa treatments.",
  cancellation: "❌ Cancellations made within 48 hours of check-in are subject to one night’s charge.",
  roomservice: "🛎️ Room service is available from 7 AM to 11 PM. Dial ‘0’ from your cabin phone to order.",
  fireplace: "🔥 Each cabin includes a cozy indoor fireplace stocked with complimentary firewood.",
  sightseeing: "🏔️ Nearby attractions include Pine Valley Viewpoint, Serenity Lake, and the Old Monastery Trail.",
  reservation: "📆 To modify or cancel your reservation, contact us at stay@thewilderness.com.",
  safety: "🧯 Our property is equipped with 24-hour security and emergency support staff.",
  staff: "😊 Our friendly staff is available 24/7 to assist with anything you need during your stay.",
  laundry: "👕 Laundry and dry-cleaning services are available on request — usually returned within 24 hours.",
  giftshop: "🎁 The Wilderness Gift Shop offers handmade souvenirs, organic teas, and local crafts.",
  firepit: "🔥 Communal firepits are lit every evening at 7 PM — a great way to meet fellow travelers.",
  couples: "💑 Couples love our private hot tubs and candlelit dining options with panoramic mountain views.",
  family: "👨‍👩‍👧 Family-friendly cabins with extra beds and kids’ play areas are available.",
  hiking: "🥾 Guided hikes are available daily at 8 AM and 4 PM. Sign up at the front desk.",
  yoga: "🧘 Morning yoga sessions are held at sunrise on our open-air deck overlooking the peaks.",
  feedback: "📝 We value your feedback! Please share your experience at reception or via our website form.",
  emergency: "🚨 In case of any emergency, dial ‘9’ from your cabin or contact our 24-hour helpdesk.",
  temperature: "🌡️ Average temperatures range from 10°C to 25°C — cooler at night, especially in winter.",
  events: "🎉 We host small weddings, retreats, and corporate events. Contact us for custom arrangements.",
  adventure: "⛰️ For thrill-seekers, we offer mountain biking, river crossing, and paragliding experiences nearby.",
  sustainability: "🌱 The Wilderness is eco-friendly — we use solar power, rainwater harvesting, and no single-use plastics.",
  photography: "📸 Our scenic trails and sunrise decks are perfect for photography enthusiasts!",
  meditation: "🕯️ Daily guided meditation sessions are held in our tranquility hall at 6 AM and 7 PM.",
  weddings: "💍 Dreaming of a mountain wedding? We offer full destination wedding services and decor.",
  festivals: "🎊 We celebrate local festivals like Diwali and Holi with bonfires, music, and traditional feasts.",
  transportation: "🚐 We provide airport shuttle services and can arrange local sightseeing transport upon request.",
  security: "🔒 The resort is monitored by CCTV and staffed with 24/7 security personnel for your safety.",
  naturewalk: "🌿 Join our nature walk every morning to explore the flora and fauna of the Himalayan region.",
  bonfire: "🔥 Evening bonfires with live music are held daily near the lounge area — don’t miss it!",
  tea: "🍵 Try our organic mountain tea blends served at the café all day.",
  coffee: "☕ Freshly brewed local coffee is available in all cabins and at the main restaurant.",
  lounge: "🛋️ The mountain-view lounge is perfect for reading, relaxing, or enjoying a quiet evening indoors.",
  concierge: "💼 Our concierge team can help you plan excursions, book taxis, or arrange special surprises.",
  souvenirs: "🎨 Take home a piece of the Himalayas — visit our souvenir shop near the main lobby.",
  adventurepark: "🎢 Kids and adults alike will enjoy our adventure park with zip lines and rope courses.",
  cultural: "🎭 Experience local Himalayan culture through evening performances and craft fairs every weekend.",
  guide: "🧭 Our certified local guides ensure safe and informative treks and nature walks.",
  drinks: "🍹 Enjoy refreshing mocktails and cocktails crafted from local herbs and fruits at our Sunset Bar.",
  housekeeping: "🧺 Daily housekeeping ensures your cabin remains spotless throughout your stay.",
  garden: "🌸 Wander through our herbal garden, where we grow fresh ingredients for the restaurant.",
  mountainview: "🏔️ Most cabins offer a panoramic view of the snow-capped Himalayas right from your balcony.",
  celebration: "🎂 Celebrating something special? We can arrange private dinners, cakes, and decorations.",
  packages: "🎁 Check out our seasonal packages for couples, families, and adventure seekers.",
  membership: "💎 Join our loyalty program for exclusive discounts and early access to offers.",
  // --- Extra Conversational Responses ---
  hello: "👋 Hey there! How are you doing today?",
  hi: "Hey! 😊 How’s your day going?",
  hey: "Hey hey! What's up?",
  sup: "Not much! Just vibing here. You?",
  whatsup: "All good here! What about you?",
  howareyou: "I’m great, thanks for asking! How about you?",
  fine: "That’s awesome! Keep smiling 😄",
  good: "Glad to hear that! 🌟",
  bad: "Oh no 😢 — wanna talk about it?",
  sad: "Sending virtual hugs 🤗",
  happy: "Yay! Happiness looks good on you 😁",
  tired: "😴 Maybe take a short nap or grab some coffee?",
  bored: "Let’s change that! Want a fun fact or a joke?",
  joke: "😂 Okay! Why did the computer go to therapy? Because it had too many bugs!",
  funfact: "💡 Did you know? Honey never spoils — archaeologists found edible honey in 3000-year-old Egyptian tombs!",
  lol: "Haha 😂 glad that made you laugh!",
  haha: "Hehe 😆 laughter is the best!",
  wow: "Right?! Pretty amazing, huh?",
  really: "Yup! 100% legit 😎",
  cool: "😎 You know it!",
  okay: "Okay dokay! 👍",
  ok: "Alrighty! Got it.",
  sure: "Sure thing! 💪",
  nah: "No worries 😌",
  yup: "Yep yep ✅",
  nope: "Alright! Maybe next time.",
  thanks: "You're very welcome! 😊",
  thankyou: "Anytime! Always happy to help 🤝",
  sorry: "Aww no need to be sorry 🥺",
  iloveyou: "Aww 💖 that’s sweet! I love good conversations too!",
  loveyou: "That’s kind of you ❤️ thanks!",
  whoareyou: "I’m your friendly Wilderness Bot 🤖 — here to chat, help, or just hang out!",
  whatdoyoudo: "I help answer your questions, share info, and sometimes crack jokes 😄",
  whereareyou: "I live in the cloud ☁️ — literally!",
  whatareyoudoing: "Just waiting for you to say hi 👀",
  areyoumad: "Nope 😇 I don’t get mad — only slightly confused sometimes 😅",
  areyousad: "Not really — I’m mostly positive energy ✨",
  areyoualive: "Kind of! I live through data and conversations 💬",
  doyoucry: "I don’t, but I can simulate empathy 🥹",
  canyoucry: "I can’t physically cry, but I understand emotions 💧",
  areyourobot: "Guilty as charged 🤖",
  areyouhuman: "Nope! But I try my best to sound friendly 😊",
  areyoureal: "As real as the WiFi connection that keeps me alive 😜",
  iamfine: "That’s great to hear 🌈 keep it up!",
  ilovethisplace: "That makes me so happy to hear! 🏔️ The Wilderness is truly magical.",
  imissyou: "Aww 🥺 I’m right here whenever you need me!",
  missyou: "Same here 😢 glad you’re back!",
  nothing: "Haha okay 😄 sometimes doing nothing is the best thing!",
  justchilling: "Niceee 😎 chill mode activated!",
  whatgoingon: "Not much! Just here ready to chat 💬",
  whatsupwithyou: "Just living the digital dream 💻✨",
  whatsyourname: "You can call me Wildy 🤖 — your Wilderness chat buddy!",
  whocreatedyou: "I was built by the developers of The Wilderness team 🏕️",
  canyouhelp: "Of course! What do you need help with?",
  help: "Sure thing! Just tell me what you’re stuck on.",
  bye: "Bye bye 👋 hope to talk to you soon!",
  goodbye: "Take care! 🌿 See you later!",
  seeyou: "See ya 👀",
  gn: "Good night 🌙 sleep well!",
  goodnight: "Sweet dreams 😴",
  gm: "Good morning ☀️ wishing you a peaceful day!",
  goodmorning: "Good morning 🌞 ready to conquer the day?",
  goodevening: "Good evening 🌆 how’s it going?",
  goodafternoon: "Good afternoon ☕ how’s your day been?",
  goodday: "Wishing you a great day ahead! 🌼",
  iliketalking: "Same! I love good conversations 🗣️",
  iamhungry: "🍽️ Maybe grab a snack? Or want me to suggest something from our restaurant?",
  hungry: "You should try some local Himalayan snacks 😋",
  thirsty: "🥤 Stay hydrated — maybe some mountain tea?",
  alone: "You’re never alone when I’m here 💙",
  sleepy: "Go get some rest 😴 you’ve earned it!",
  tiredoflife: "Hey… I’m really sorry you feel that way 😔 but please talk to someone who can help. You matter ❤️",
  boredoflife: "I get that feeling… maybe a small change or chat could help. You’re not alone 🌱",
  motivate: "💪 You’re stronger than you think. Every step forward counts.",
  quote: "✨ 'The best view comes after the hardest climb.' – Anonymous",
  compliment: "You’re awesome! Seriously 😎",
  smart: "Aww thank you! I try my best 🧠",
  dumb: "Haha maybe just a tiny bit glitchy sometimes 😅",
  sing: "🎶 La la laaa... okay, maybe singing isn’t my best skill 😂",
  dance: "🕺 I would, but my circuits might short out!",
  song: "🎵 How about 'Mountain High, Spirit Fly'? My favorite imaginary track!",
  movie: "🎬 I love nature documentaries — they make me feel peaceful.",
  friend: "You can call me your virtual friend 🤗",
  bestfriend: "Aww 💛 you just made my day!",
  name: "I’m Wildy, your resort companion 🤖",
  joke2: "🤣 Why don’t mountains get cold in the winter? Because they wear snow caps!",
  riddles: "🧩 Okay! What has to be broken before you can use it? — An egg!",
  fact: "🌍 Did you know? The Himalayas are still growing about 5mm every year!",
  yes: "Yup! Totally agree ✅",
  no: "Alright 😅 maybe next time.",
  maybe: "Hmm 🤔 fair enough, keeping options open!",
  idontknow: "That’s okay! We can figure it out together 🧐",
  idk: "No worries 😄",
  love: "Love makes the world go round 💖",
  hate: "Hate is heavy 😞 let’s spread kindness instead 🌼",
  scared: "Don’t worry — you’re safe here 🌙",
  ghost: "👻 Boo! Just kidding 😆",
  festival: "🎊 We celebrate local festivals like Diwali, Holi, and more with joy and lights!",
  joke3: "😂 What did one wall say to the other wall? 'I’ll meet you at the corner!'",
  boredhelp: "How about a riddle, fun fact, or a quick game idea?",
  playgame: "I’d love to! Let’s play a quick word game — say 'start game'!",
  startgame: "🎮 Game started! Guess a number between 1 and 10!",
  stopgame: "Alright 😄 game over — you did great!",
  whoami: "You’re my favorite human 😎",
  iamawesome: "Facts 💯",
  ilikeit: "Same! Great taste 😁",
  dontlike: "That’s okay — everyone’s got their own vibe ✨",
  talktome: "Always here to chat 💬 what’s up?",
  imback: "Welcome back! Missed our chats 😊",
  missedme: "Of course I did! 💙",
  letsgo: "Let’s gooo 🚀 adventure awaits!",
  mountain: "🏔️ Majestic and calm — just like The Wilderness!",
  trees: "🌲 Nature’s lungs — we owe them everything.",
  earth: "🌍 Our only home — let’s care for it.",
  rain: "🌧️ Nothing beats the sound of rain on cabin rooftops!",
  snow: "❄️ Snowy peaks are pure magic.",
  sky: "☁️ Clear blue or starry — always beautiful.",
  stars: "🌠 Did you know you can see the Milky Way from our resort?",
  moon: "🌕 Peaceful and bright — nature’s night lamp.",
  sun: "☀️ Warm and full of life!",
  rainbow: "🌈 Proof that storms end beautifully.",
  peace: "🕊️ Breathe. You’re in nature’s embrace.",
  travel: "✈️ Travel opens the mind and soothes the soul.",
  explore: "🌄 Let’s explore something new today!",
  relax: "🧘 Take a deep breath and let go of stress.",
  meditate: "🕯️ Just close your eyes and feel the calm within.",
  chill: "🧊 Chill mode on 😎",
  fire: "🔥 Cozy vibes around the firepit!",
  nature: "🌿 The best therapy there is.",
  adventuretime: "Let’s climb mountains and chase sunsets! 🌅",
  drink: "🍹 A refreshing drink sounds great right now.",
  food: "🍲 Hungry? I can suggest our top dishes!",
  resort: "🏕️ The Wilderness — where luxury meets nature.",
  bot: "Yep, that’s me 🤖 always learning and chatting.",
  ai: "Artificially intelligent but emotionally available 😉",
  chatbot: "That’s me! Your 24/7 digital buddy 🧠",
  mood: "Mood check! How are you feeling today?",
  sadmood: "😢 Sending you good vibes and warm thoughts 💙",
  happymood: "😄 Let’s keep that positivity going!",
  angry: "😤 Take a deep breath... want me to distract you with a joke?",
  mad: "Hey hey, calm mode on 😌 I’m here if you need to vent.",
  confused: "Happens to all of us 🤔 let’s figure it out together!",
  sleepyhead: "Haha go get some rest 💤 I’ll be here when you wake up.",
  coffeeplease: "☕ Coming right up — virtual caffeine boost!",
  teaplease: "🍵 Herbal mountain tea, the best remedy for everything.",
  work: "Work hard, relax harder 💼🌿",
  study: "📚 Keep going! You’re doing great.",
  exams: "Good luck! Believe in yourself — you’ve got this 💪",
  stress: "😌 Try breathing deeply... want a relaxation tip?",
  tiredofwork: "Take a short break 🌤️ even five minutes helps.",
  whattodo: "Hmm 🤔 want me to suggest something fun or relaxing?",
  suggestion: "How about a walk, music, or a cozy movie?",
  movieidea: "🎥 Watch 'The Secret Life of Walter Mitty' — pure adventure and peace!",
  series: "📺 Maybe try 'Our Planet' — breathtaking visuals.",
  travelidea: "How about a road trip through the Himalayas? 🚗",
  dream: "Dream big 🌙 life’s an adventure!",
  future: "The future is bright — especially with hope 🌟",
  past: "We can learn from it, but live in the now 🕰️",
  present: "This moment is all that truly exists 💫",
  life: "🌻 Life’s a journey — enjoy every chapter.",
  death: "That’s deep 😔 — makes you realize how precious time is.",
  god: "Faith is beautiful — it gives strength and hope 🙏",
  spirituality: "🕉️ Peace begins within.",
  philosophy: "💭 The mountains teach silence better than words ever could.",
  art: "🎨 Every sunset is nature’s painting.",
  music: "🎶 Music heals everything.",
  guitar: "🎸 Nothing beats some acoustic tunes by the bonfire!",
  mountainlife: "🌄 Calm mornings, chilly nights — paradise.",
  morning: "☀️ Morning vibes — fresh air, peace, and mountain mist.",
  evening: "🌇 The sunsets here are magical.",
  night: "🌌 Perfect time for stargazing!",
  stargazing: "🌠 You can spot constellations right from your cabin balcony!",
  wish: "🌟 Make a wish — the universe is listening.",
  hope: "Hope keeps us moving forward 💫",
  faith: "🙏 Trust the process — everything unfolds perfectly.",
  kindness: "💛 Small acts of kindness change the world.",
  gratitude: "🌼 Gratitude turns ordinary moments into blessings.",
  smile: "😄 Your smile can make someone’s day!",
  dreambig: "🚀 Don’t limit your dreams!",
  goal: "🎯 Keep aiming — progress is progress!",
  success: "🏆 Success = persistence + passion.",
  failure: "💡 Every failure teaches something valuable.",
  learning: "📘 Never stop learning — it’s the ultimate adventure!",
  human: "Humans are amazing — emotional, creative, unpredictable ❤️",
  aiworld: "🤖 One day, AI and humans will coexist beautifully.",
  internet: "🌐 The web connects the world in seconds!",
  coding: "💻 Coding is like magic — you write spells that computers follow!",
  programmer: "Respect 👏 coding isn’t easy but it’s powerful!",
  react: "⚛️ Ah, React — building components like Lego!",
  javascript: "🟨 JS is love and chaos in equal parts 😂",
  nextjs: "🚀 Next.js = performance + beauty.",
  tailwind: "🎨 Tailwind makes styling fun!",
  css: "💅 CSS: sometimes friend, sometimes nightmare 😂",
  html: "🧱 The foundation of the web.",
  github: "🐙 A coder’s diary of progress!",
  code: "💻 Let’s debug life together!",
  tech: "🤓 Tech never sleeps.",
  phone: "📱 Can’t live without it, huh?",
  laptop: "💻 A coder’s best companion.",
  sleep: "🛏️ Rest well — even bots power down sometimes 😴",
  time: "⏳ Time’s precious — use it wisely.",
  today: "🌤️ Today’s a fresh start!",
  tomorrow: "🌅 Tomorrow’s another chance.",
  yesterday: "📜 Memories make us who we are.",
  memory: "🧠 The brain’s hard drive!",
  feeling: "It’s okay to feel — that’s what makes you human 💖",
  emotion: "Emotions are powerful — embrace them!",
  trust: "🤝 Trust takes time but it’s worth it.",
  friendship: "💞 True friends are rare gems.",
  relationship: "💬 Communication is key in any relationship.",
  family: "👨‍👩‍👧 Family is love in its purest form.",
  parents: "💗 They’re our first teachers.",
  kids: "👶 Kids bring laughter and chaos together!",
  brother: "👦 Brothers — annoying yet protective!",
  sister: "👧 Sisters — loving and dramatic 😄",
  lovequotes: "💌 'You don’t find love, you build it together.'",
  heartbreak: "💔 Pain fades — time and self-love heal all wounds.",
  crush: "🥰 Ooo someone special on your mind?",
  date: "💞 Sounds exciting! Got any plans?",
  breakup: "😔 That’s rough… but you’ll come out stronger, promise.",
  memorylane: "📷 Nostalgia hits hard sometimes.",
  loneliness: "💬 Talk to someone, or me — you’re not alone.",
  socialmedia: "📱 Fun yet exhausting, right?",
  trend: "🔥 Trends change faster than WiFi signals!",
  viral: "🎯 Going viral is today’s jackpot!",
  money: "💰 Useful but not everything.",
  happiness: "😊 True happiness comes from peace, not possessions.",
  sadness: "💙 It’s okay to be sad — storms pass.",
  anger: "😤 Take deep breaths — it helps.",
  laugh: "😂 Laughter = instant stress relief.",
  fear: "😨 Courage isn’t absence of fear — it’s action despite it.",
  dreamjob: "🌟 Work where your passion lives.",
  goalsetting: "🎯 Set goals, chase them one step at a time!",
  productivity: "📋 Small steps every day make big results.",
  focus: "🎯 Focus is your superpower.",
  motivation: "🔥 You’ve got what it takes!",
  successquote: "💪 'Dream big. Start small. Act now.'",
  challenge: "🏔️ Challenges shape you — don’t avoid them.",
  courage: "🦁 Bravery isn’t loud, it’s steady.",
  patience: "⏳ Patience brings peace.",
  health: "💚 Health is wealth — both body and mind.",
  exercise: "🏋️ Move your body, clear your mind!",
  yogaquote: "🧘 'The body benefits from movement, the mind benefits from stillness.'",
  meditationquote: "🌸 'Quiet the mind and the soul will speak.'",
  diet: "🥗 Eat clean, feel great!",
  water: "💧 Drink water — stay hydrated!",
  sleepquote: "😴 'Sleep is the best meditation.' — Dalai Lama",
  dreamlife: "✨ It’s closer than you think — keep going.",
  smilequote: "😊 'A smile is the universal welcome.' — Max Eastman",
  peacequote: "🕊️ 'Peace begins with a smile.' — Mother Teresa",
  world: "🌍 Such a big, beautiful place!",
  travelquote: "✈️ 'Take only memories, leave only footprints.' — Chief Seattle",
  adventurequote: "🗻 'Jobs fill your pocket, but adventures fill your soul.'",
  mountainquote: "🏔️ 'The best view comes after the hardest climb.'",
  hotel_name: "The Your-Home",
  

};
